FROM eclipse-temurin:17-jdk-alpine
LABEL authors="lmello"

VOLUME /tmp

ARG DATASOURCE_URL
ARG DATASOURCE_USERNAME
ARG DATASOURCE_PASSWORD

COPY target/*.jar app.jar

ENV DATASOURCE_URL=${DATASOURCE_URL}
ENV DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
ENV DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}

ENTRYPOINT ["java", "-jar", "/app.jar"]