package com.lmello.bookstore.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lmello.bookstore.dto.BookDTO;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.util.List;

@DynamoDBTable(tableName = "Book")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Book {
    @Id
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @JsonIgnore
    private String id;

    @DynamoDBAttribute(attributeName = "author")
    @JsonProperty
    private String author;

    @DynamoDBAttribute(attributeName = "title")
    @JsonProperty
    private String title;

    @DynamoDBAttribute(attributeName = "url")
    @JsonProperty
    private String url;

    @DynamoDBAttribute(attributeName = "synopsis")
    @JsonProperty
    private String synopsis;

    @DynamoDBAttribute(attributeName = "tags")
    @JsonProperty
    private List<String> tags;

    @DynamoDBAttribute(attributeName = "content")
    @JsonProperty
    private List<String> content;

    @DynamoDBAttribute(attributeName = "active")
    @JsonProperty
    private Boolean active;

    public Book(BookDTO bookDTO) {
        this.author = bookDTO.author();
        this.title = bookDTO.title();
        this.url = bookDTO.url();
        this.synopsis = bookDTO.synopsis();
        this.tags = bookDTO.tags();
        this.content = bookDTO.content();
        this.active = true;
    }
}
